# Database configuration
spring.datasource.url = url
spring.datasource.username = username
spring.datasource.password = password

# JPA and Hibernate configuration
spring.jpa.open-in-view = false
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = false
spring.jpa.properties.hibernate.format_sql = false

# Logging configuration
logging.level.org.hibernate.SQL = ERROR
logging.level.org.hibernate.type.descriptor.sql = OFF

# OpenAPI/Swagger configuration
springdoc.api-docs.path = /json
springdoc.swagger-ui.path = /doc
springdoc.swagger-ui.operationsSorter = alpha